on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '1.7.10'
        type: choice
        options:
        - 1.7.10
        - 1.12.2
        - 1.19.2

jobs:
 job1:
   if: ${{input.version}} == '1.7.10'
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: download 
        run: wget https://github.com/Gyxqq/mcserver_downloader/releases/download/server/server_1.7.10.jar
      - name: build 
        run: java -jar server_1.7.10.jar
      - name: tar
        run: tar -cf server.tar *
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: server
          path: server.tar
          retention-days: 1
