on:
  workflow_dispatch:
    inputs:
        tags:
        description: 'Test scenario tags'
        required: true
        type: choice
        options:
        - 1.12
        - 1.19
        - 1.7.10


jobs:
 job1:
  job2:
    needs: job1
    
  
